### ISSUE TITLE
CSS for table

### ISSUE THREAD

**Issue by pnrobinson** [P2GX/maxodiff#74]
If we replace the current ``.countsTable th``with the following:

```css

.countsTable th {
    position: relative;
    height: 200px;
    width: 50px; /* needed for layout */
    padding: 0;
    margin: 0;
    overflow: visible;
    white-space: nowrap;
    vertical-align: bottom;
    text-align: center;
}

.countsTable th > div {
   /*  transform: rotate(315deg); or -45deg */
    transform-origin: bottom left;
    position: absolute;
    bottom: 0;
    left: 50%;
    transform: translateX(+0%) rotate(315deg); /* better centering */
    white-space: nowrap;
}
```

and wrap the contents of the table ``th``cells with **div**, we get nicer placement of the headers. For instance

```html
  <th onclick="window.open(&#39;https://hpo.jax.org/browse/term/HP:0009909&#39;)"
                    style="color: blue"><div>Uplifted earlobe</div></th>
```
