### ISSUE TITLE
Put each disease in a CSS box

### ISSUE THREAD

**Issue by pnrobinson** [P2GX/maxodiff#76]
Here are some suggestions for improving the CSS
1) Put each MAXO term section into its own box
Add the following to the CSS
```css
.section-box {
  border: 1px solid #ccc;
  border-left: 6px solid #007acc;
  border-radius: 8px;
  padding: 1em;
  margin: 2em 0;
  background: #f9f9f9;
  box-shadow: 0 2px 4px rgba(0,0,0,0.05);
}

.section-box h2 {
  font-size: 1.4em;
  color: #003366;
  margin-bottom: 0.5em;
}
```
wrap the sections
```html
<div class="section-box">
  <h2>2) MAXO:0000706: otolaryngologist evaluation</h2>
(...)
</div>
````

2) Add some styling for the score table
-remove current .scoreTable css
-add this
```css
.scoreTable {
  width: auto;
  border-collapse: collapse;
  margin-bottom: 1em;
}

.scoreTable td {
  padding: 0.3em 0.6em;
  border: none;
  font-size: 0.95em;
}
````

3) Remove "Table of HPO Term Repetition Counts" (redundant)
